# Netlify Configuration
# Set DATABASE_URL environment variable in Netlify UI:
# Site settings > Environment variables > Add a variable
# Key: DATABASE_URL
# Value: Your PostgreSQL connection string

[build]
  command = "npm run build && rm -rf dist/client && cp -r dist/public dist/client"
  publish = "dist/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]
